### ISSUE TITLE
Create smart build and deployment routine

### ISSUE THREAD

**Issue by aboutaaron** [crayhola/crayhola.github.io#3]
Make sure we don't overwrite the CNAME and ensure build and dev environments are separate.

**Comment by erikreyna** [comment]
This has been resolved. 

Moving the CNAME file into the source directory allows it to be copied.

See: https://github.com/thoughtbot/proteus-middleman/wiki/Publishing-to-Github-Pages'-User-or-Organization-Pages

All development and deployments should happen from the development branch.
